<a href="https://colab.research.google.com/github/kkknewbie9/MchineLrn/blob/main/Day14_part3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv('/content/Wine.csv')

x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
# we need to separate the dataset into training and testing

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.25)


In [4]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [5]:
from sklearn.decomposition import PCA
pca = PCA(n_components = 2)
x_train = pca.fit_transform(x_train)
x_test = pca.transform(x_test)

In [6]:
pca

PCA(copy=True, iterated_power='auto', n_components=2, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [7]:
# Checking the performance of PCA with logistic regression

from sklearn.linear_model import LogisticRegression

classifier = LogisticRegression(random_state = 0)

classifier.fit(x_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [9]:
# COnfusion matrix

y_pred = classifier.predict(x_test)

from sklearn.metrics import confusion_matrix, accuracy_score

cm = confusion_matrix(y_pred, y_test)

print(cm)  #we are getting 3X3 matrix for confusion matrix, as there can be neutral values too. SO separately given
accuracy_score(y_pred, y_test)

[[15  0  0]
 [ 1 19  0]
 [ 0  0 10]]


0.9777777777777777

In [10]:
y_pred

array([2, 1, 2, 2, 2, 2, 1, 1, 2, 1, 3, 3, 2, 1, 1, 2, 3, 1, 3, 2, 2, 2,
       2, 1, 1, 2, 3, 2, 1, 2, 3, 3, 2, 1, 2, 2, 1, 3, 3, 1, 1, 3, 2, 2,
       1])